name: Latest Post Workflow


on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-blog:
    name: Update Repo
    runs-on: ubuntu-latest
    steps:
      - name: Profile Readme Stats
        uses: teoxoy/profile-readme-stats@v1

